language: java
addons:
  sonarcloud:
    organization: inveasy

script:
- mvn clean install sonar:sonar -Dsonar.login=${SONAR_LOGIN} -B -V
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

deploy:
- provider: releases
  api_key:
    secure: bS8H1GXMwgU2OxtJtMzDHHfi+s5oUdGTUC0zeQF/+/YpMlkrv28BRX85kYgX7M0Mn0GkEwnjfSSuZeieRWlw0tCK8gNjtu16kAONWu9Sp+wkzagnJ1U3ArIyidTeXd6zkShSwR/DTZm7bGxnoDx6dPDFLm7L+6vp9JPcq5rMykJMdNudBmGwYx3ZcNQ6P5wYtCbVrPYFu+qLTul/FlYKcFAtQ2vAoYGrFc0jr9lkDAUlIF6P5qRRW03Dn1E9AahVxs79QO0beO6KUmTgPl+WUx4KIZ240etSIKbBDpxx1KtzUTre6Ca2uXmr7QrjTIRE1fmCZbR1iM/0VVwsX2lPwzHTAlRODeFiKeEWsH0jdb4Nx81zy7DmEQyBMWSX5DK1ffrWxtF65cBm+96m4x5sa8uExGJ8mY0v/Qta7lBzOzpuAtj4vx/PBC7vJ8LyHRoTMjnDfdtu4EISYw91nhmyvy+zI3DIXte6zWZRH/Xh8tiAhD161eWPkGJfR9FMeTrue33mGuZef0S0N/S/XFN1YeWtrmawGe32+5+FGxlcXVfAJvIVhG1MYJwiy25jeuzmCnU2XFFg39OOS0oIqg9u1Pa+lOFvX1G3guJ1HoP9XGxEdzxKSmTCxWTNMqZ3zx9KKfxwTDa9lN5a9aUFQl1fRPhxNrvckUslRd+mbBPpMW4=
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    tags: true
- provider: bintray
  file: bintray-descriptor.json
  key:
    secure: bcH0p3lGOqGb6PIXMvnsCKWBt1FE38x5+Zeeitg1VoAXjOIa1tHI602yUP2Fv7ikdpVirEoN4aGbj0H1ZLpTGWJx7ExSrHqWPsFInbG/G8+5m750JD3X8yOGX459cH5mux/9a+oiUh2CtDBq+NKsTEk4JClex67qMwnYCrc8lZ70cQYQEZH/fD1p94Qef+dLdsXXma69iyNtTUJKtrsNUq/MU7FVWyrsiI+e0SOf0y8MtzQz8UwNddEYVETlhc7QfXH6FYnMNUmm6qr0RNlm9OwDm6DNwehyAIf1QttqxE+hiiNjl6YgOAw9mNEdSyhqMsE0sz1MfritrhWnJMcPJxqitxjXvVUpJHDpWzew6JS6Yvsq6KaPoNcncDeM1V9N88VE2HEwgNQC28sy0qQWemXSt5W7EPbGwtoGRDKX4oxIUxasbF8QcCBV+aQtpS6pzNHEBxWpBklZNKYWj8CY0BdHcqmJda7575XZrUfG8DXZTw/INcqKS1Ktxa+3UkSlxfvIXv6h8V7XuQj2h8JkbyNll7uIYws5uOnEE4sSBW2q2oGUvR++FyDjn5tcA4Sazq6psdy43ndtVcHYVKHElGQve0VRD+nCn+NlZmFx/x6rxtt95puyN40jErhJ9uio/RUJsRZSjHcruZEch3QO5I0PDsHJikEkGZl2FplxSxw=
  user: goveranter
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    tags: true